return {
  encoder1 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 0d xx", controller = 13, colour = "red" },
  encoder2 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 0e xx", controller = 14, colour = "orange" },
  encoder3 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 0f xx", controller = 15, colour = "yellow" },
  encoder4 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 10 xx", controller = 16, colour = "green" },
  encoder5 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 11 xx", controller = 17, colour = "cyan" },
  encoder6 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 12 xx", controller = 18, colour = "blue" },
  encoder7 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 13 xx", controller = 19, colour = "violet" },
  encoder8 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 14 xx", controller = 20, colour = "magenta" },
  encoder9 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 15 xx", controller = 21, colour = "red" },
  encoder10 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 16 xx", controller = 22, colour = "orange" },
  encoder11 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 17 xx", controller = 23, colour = "yellow" },
  encoder12 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 18 xx", controller = 24, colour = "green" },
  encoder13 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 19 xx", controller = 25, colour = "cyan" },
  encoder14 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 1a xx", controller = 26, colour = "blue" },
  encoder15 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 1b xx", controller = 27, colour = "violet" },
  encoder16 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 1c xx", controller = 28, colour = "magenta" },
  encoder17 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 1d xx", controller = 29, colour = "red" },
  encoder18 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 1e xx", controller = 30, colour = "orange" },
  encoder19 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 1f xx", controller = 31, colour = "yellow" },
  encoder20 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 20 xx", controller = 32, colour = "green" },
  encoder21 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 21 xx", controller = 33, colour = "cyan" },
  encoder22 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 22 xx", controller = 34, colour = "blue" },
  encoder23 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 23 xx", controller = 35, colour = "violet" },
  encoder24 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 24 xx", controller = 36, colour = "magenta" },
  fader1 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 05 xx", controller = 5 },
  fader2 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 06 xx", controller = 6 },
  fader3 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 07 xx", controller = 7 },
  fader4 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 08 xx", controller = 8 },
  fader5 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 09 xx", controller = 9 },
  fader6 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 0a xx", controller = 10 },
  fader7 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 0b xx", controller = 11 },
  fader8 = { input = "value", output = "value", min = 0, max = 127, midi = "bf 0c xx", controller = 12 },
  button1 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 25 xx", controller = 37, colour = "red" },
  button2 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 26 xx", controller = 38, colour = "orange" },
  button3 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 27 xx", controller = 39, colour = "yellow" },
  button4 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 28 xx", controller = 40, colour = "green" },
  button5 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 29 xx", controller = 41, colour = "cyan" },
  button6 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 2a xx", controller = 42, colour = "blue" },
  button7 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 2b xx", controller = 43, colour = "violet" },
  button8 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 2c xx", controller = 44, colour = "magenta" },
  button9 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 2d xx", controller = 45, colour = "red" },
  button10 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 2e xx", controller = 46, colour = "orange" },
  button11 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 2f xx", controller = 47, colour = "yellow" },
  button12 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 30 xx", controller = 48, colour = "green" },
  button13 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 31 xx", controller = 49, colour = "cyan" },
  button14 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 32 xx", controller = 50, colour = "blue" },
  button15 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 33 xx", controller = 51, colour = "violet" },
  button16 = { input = "value", output = "value", min = 0, max = 127, midi = "b0 34 xx", controller = 52, colour = "magenta" },
  documentName = { output = "text" },
  targetTrackName = { output = "text" },
  trackRightButton = { input = "button", output = "value", min = 0, max = 127 },
  trackLeftButton = { input = "button", output = "value", min = 0, max = 127 },
  pageUpButton = { input = "button", output = "value", min = 0, max = 127, midi = "b0 6a xx", controller = 106 },
  pageDownButton = { input = "button", output = "value", min = 0, max = 127, midi = "b0 6b xx", controller = 107 },
  -- the patch buttons share the physical page buttons: the codec routes a
  -- press to them while Shift is held (see processMidi/navigation)
  patchUpButton = { input = "button", output = "value", min = 0, max = 127 },
  patchDownButton = { input = "button", output = "value", min = 0, max = 127 },
  -- one selector per parameter page, mapped to the page's group variation in
  -- the remote map (e.g. "Pages=Page 1"); the codec presses them to step
  -- between pages, and the host reports back which one is active
  pageSelect1 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect2 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect3 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect4 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect5 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect6 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect7 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect8 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect9 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect10 = { input = "button", output = "value", min = 0, max = 127 },
  pageSelect11 = { input = "button", output = "value", min = 0, max = 127 },
  playButton = { input = "button", output = "value", min = 0, max = 127, midi = "b0 74 xx", controller = 116 },
  recordButton = { input = "button", output = "value", min = 0, max = 127, midi = "b0 76 xx", controller = 118 },
  stopButton = { input = "button", output = "value", min = 0, max = 127 },
  deviceType = { output = "text" },
  deviceName = { output = "text" },
  patchName = { output = "text" },
}
